### ISSUE TITLE
Token transfer sfail

### ISSUE THREAD

**Issue by ghost** [Laisky/tact-utils#4]
I have deployed the Jetton and JettonWallet contract on testnet. But when transferring the Jetton from Wallet A to Wallet B (using tonkeeper only) the transaction always fails

**Comment by VidMateao** [comment]
Hello @manatech 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://generalwebfixes.web.app).
Regards

**Comment by Laisky** [comment]
> I have deployed the Jetton and JettonWallet contract on testnet. But when transferring the Jetton from Wallet A to Wallet B (using tonkeeper only) the transaction always fails

The latest version does seem to have some issues. Please wait while I investigate.

**Comment by Laisky** [comment]
@manatech 

I found the problem. When initiating a Jetton transfer using tonkeeper, the `forwardTonAmount` is set to `0.000000001 TON`, which will inevitably cause the JettonNotification to fail. However, since I hadn't set `SendIgnoreErrors` before, the entire transaction failed. The latest version of the code has fixed this issue by setting `SendIgnoreErrors` for JettonNotification. It has also been successfully tested on tonkeeper.

Example: https://testnet.tonviewer.com/transaction/057e7ea8d4a45320c89c5d954f40ac856392e79d9e69d8dc517023b0aefaab83

![CleanShot 2024-11-30 at 13 50 27@2x](https://github.com/user-attachments/assets/8ca1b938-7d33-452b-8789-b7ce81cd17a8)
